SiliconLabsSoftware/z-wave-protocol-controller

.github/workflows/build-rootfs.yml
CMakeLists.txt
cmake/include/doxygen.cmake
cmake/modules/FindPlantUML.cmake
helper.mk
scripts/build-rootfs.sh

SWPROT-8953: build: Generate a doc package

---

helper.mk

Note this commit could be improved if applied to other base,
Observed issue (not present on current base with removed dirs):
failed to create symbolic link '/usr/local/opt/unifysdk/components/uic_rust' because existing path cannot be removed: Is a directory
failed to create symbolic link '/usr/local/opt/unifysdk/components/unify_attribute_poll' because existing path cannot be removed: Is a directory
It did not break while it should.
Also it has been observed that it fails to build on GH.
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/pull/19

SWPROT-8953: build: Enable image provider

---

NEWS.md
README.md
applications/zpc/Cargo.lock
applications/zpc/components/Cargo.lock
applications/zpc/release_notes.md
cmake/modules/FindUnifySDK.cmake
components/Cargo.lock
helper.mk
scripts/build/build_documentation.py

To be merged after:
- https://github.com/SiliconLabs/UnifySDK/releases/tag/ver_1.7.0
-  https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/settings/secrets/actions/
UNIFYSDK_GIT_REPOSITORY
- https://github.com/SiliconLabsSoftware/z-wave-protocol-controller
- https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/pull/30
- https://siliconlabssoftware.github.io/z-wave-protocol-controller Shows RC11
- https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/pull/36
- https://github.com/Drewsif/PiShrink/blob/master/LICENSE
- https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/releases/tag/ver_1.7.0-RC11
- [check doc](https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/tree/main/applications/zpc/doc/supported_command_classes.rst)
- …

SWPROT-8953: Release 1.7.0

---

.github/workflows/build-rootfs.yml
cmake/release-version.cmake

SWPROT-8953: ci: Pull annotated tag
After further investigations, the reason that script failed to use
the git describe in github it because of a bug in related github action
Relate-to: https://github.com/actions/checkout/pull/2081
Origin: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/pull/42
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/pull/35

SWPROT-8953: cmake: Drop vers_1.7.0 hardcoded version

---

.gitattributes

This is something that should have been removed in latest release. It would be nice to release a revision version,
this will help also derivates projects to importing ver_1.7.1 ?

SWPROT-8953: git: Remove .gitattributes to be part of next release

---

.gitmodules

Observed issue on ver_1.7.0-27-g1302b2a5 was:
docker build https://github.com/SiliconLabsSoftware/z-wave-protocol-controller.git#main
unable to prepare context: unable to 'git clone' to temporary context directory: \
error initializing submodules: fatal: No url found for submodule path \
'applications/zpc/components/zwave/zwave_transports/s2/libs/zw-libs2/TestFramework/cmock' in .gitmodules
This was done using:
git submodule add --force \
https://github.com/throwtheswitch/cmock \
applications/zpc/components/zwave/zwave_transports/s2/libs/zw-libs2/TestFramework/cmock
git -C applications/zpc/components/zwave/zwave_transports/s2/libs/zw-libs2/TestFramework/cmock \
checkout v2.5.3-g9d092898
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/pull/57#issuecomment-270428 …

libs2/tf: Fix a/z/c/z/z/s/l/z/T/cmock submodule to v2.5.3-g9d092898

---

NEWS.md
applications/zpc/components/zwave/zwave_transports/s2/libs/zw-libs2/include/S2_external.h
applications/zpc/components/zwave/zwave_transports/s2/libs/zw-libs2/include/mock/s2_extern_mock.c
applications/zpc/components/zwave/zwave_transports/s2/libs/zw-libs2/include/s2_classcmd.h
applications/zpc/components/zwave/zwave_transports/s2/libs/zw-libs2/include/s2_protocol.h
applications/zpc/components/zwave/zwave_transports/s2/libs/zw-libs2/protocol/S2.c
applications/zpc/components/zwave/zwave_transports/s2/libs/zw-libs2/test/test_protocol.c
applications/zpc/components/zwave/zwave_transports/s2/src/zwave_s2_transport.c

Previous changes are not atomic (because comming from different context) they are now isolated and grouped in same PR.
Bug-ZPC: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/issues/50

libs2: zwave_transports: Align libs2 API in zwave_s2_transport.c (#51)

---

applications/zpc/components/zpc_attribute_store/include/attribute_store_defined_attribute_types.h
applications/zpc/components/zpc_attribute_store/src/zpc_attribute_store_type_registration.cpp
applications/zpc/components/zwave/zwave_transports/s2/CMakeLists.txt
applications/zpc/components/zwave/zwave_transports/s2/src/zwave_s2_network.c
applications/zpc/components/zwave/zwave_transports/s2/src/zwave_s2_transport.c
applications/zpc/components/zwave/zwave_transports/s2/test/CMakeLists.txt
applications/zpc/components/zwave/zwave_transports/s2/test/zwave_s2_network_test.c

SWPROT-9320 Controller NLS state storage
Merge in UIC/uic from task/ayersoz/SWPROT-9320-controller-nls-state-storage to z-wave/main
(cherry picked from commit 7a63883eb991f0f8cbbb663df8802be0764ec6e5)
Last-Update: 2025-03-05

    SWPROT-9320 Controller NLS state storage

---

patches/UnifySDK/0006-git-docker-uic-resources-Removed-as-not-part-of-Unif.patch

p/UnifySDK: Add patch to remove uic-resources (LFS)

---

patches/UnifySDK/0001-build-Relax-compiler-warnings-to-support-more-compil.patch
patches/UnifySDK/0003-tests-p-cmock-Add-0001-Added-array_as_byte-config-op.patch
patches/UnifySDK/0004-tests-build-cmake-Use-Upstream-cmock.patch
patches/UnifySDK/0005-git-Remove-.gitattributes.patch
patches/UnifySDK/0006-git-docker-uic-resources-Removed-as-not-part-of-Unif.patch

p/UnifySDK: Refresh patches series to align z-wave/core/zpc/main
For the record patches are exported from
https://github.com/SiliconLabs/UnifySDK/
git rebase -i ver_1.7.0 \
&&  git format-patch --no-numbered \
-o ~/mnt/z-wave-protocol-controller/patches/UnifySDK/ \
ver_1.7.0

p/UnifySDK: Refresh patches series to align z-wave/core/zpc/main

---

.github/workflows/build.yml
Dockerfile
cmake/modules/FindUnifySDK.cmake

Those changes were motivated to github
This extra clean step saves 3GB (11GB to 7.6GB, which is still huge)
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/10
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/15
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/7
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/2

docker: Slim down run image to save space for github

---

applications/zpc/components/zwave_command_classes/src/zwave_command_class_crc16.cpp

G++-14 was not building because "std::find_if" was missing the header \<algorithm\>.

Include header algorithms to enable build with g++-14

---

.github/workflows/test.yml

This is a workaround, to allow other related developements (in other repos not forks).
To be reverted once everything agregrated in the upstream.
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/2

ci: github: Align docker image to zpc

---

.github/workflows/test.yml

While the actions are working as expected in main branch I noticed that for other branches:
In test workflow the checkout action is not using the same rev as in the build workflow. IHMO this is an odd default beaviour...
Relate-to: https://github.com/orgs/community/discussions/157893
Realte-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/22

fix(github): Use build git rev for testing

---

applications/zpc/components/network_monitor/src/network_monitor.cpp

Now events are forwarded to C++ handler functions by reference, instead of pointers, it is safer to avoid potential use on null pointers.
So now on, previously allocated (in post) user data are freed just after handling them.
I am assuming that once events are posted, the owner is the contiki event loop, which should free events data once consumed by handler.
In other works contiki is managing the lifecyle of user data.
Note that once event is processed, the address still remain in contiki queue but no more referenced since the queue pointer is moving to the next one.
A later change for contiki can explicitly set the consumed pointer to null in consumed queue cell.
Relate-to: UIC-3659
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/17
[CLA]: …

fix(network_monitor): Delete previously allocated events in contiki

---

.github/workflows/test.yml

The change allows to block failed PRs
Relate-to: https://github.com/actions/github-script
Relate-to: https://octokit.github.io/rest.js/v21/#repos
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/22

ci: github: Propagate test run outcome to commit status

---

.github/workflows/build-rootfs.yml
.github/workflows/build.yml
.github/workflows/test.yml

Observed issue is:
Run actions/github-script@v7
(...)
RequestError [HttpError]: Resource not accessible by integration
(...)
status: 403,
response: {
(...)
request: {
method: 'POST',
url: 'https://api.github.com/repos/SiliconLabsSoftware/z-wave-protocol-controller/statuses/***',
(...)
This is caused by the repo configuration (in actions):
"Workflow permissions" : "Read repository contents and packages permissions"
Which is more restrictive that default:
"Workflow permissions" : "Read and write permissions"
There is no need to set perm in token anymore.
Extra note, to some extends tokens may be replaced with GH apps.
Relate-to: https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status Relate-to:https://github.com/SiliconLabsSoftware/z-wave-protocol-contro …

ci: github: Restrict permissions for actions, test update commit status

---

.github/workflows/test.yml

This issue was reported by CodeQL, IMHOI the alert was over reacting because contents was already extracted in a separate directory (which is absent in tree, so there is no risk to override)
An extra check would be to verify a signed asset (using GPG), along a ZWA public key shared in tree.
Potential fix for code scanning alert no. 1: Artifact poisoning
Origin: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/pull/107
Relate-to: https://github.com/Z-Wave-Alliance/OSWG/issues/48#issuecomment-2607661260
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/issues/67
Relate-to: https://github.com/rzr/z-wave-protocol-controller/security/code-scanning/1
Relate-to: https://cwe.mitre.org/data/definitions/829.html
[CLA]: …

ci: github: Harden the test workflow by downloading into temp dir

---

applications/zpc/applications/zwave_api_demo/src/zwave_api_demo_callbacks.c

Checking snprintf results, reminder :
If the output was truncated due to this limit, then the return
value is the number of characters (excluding the terminating
null byte) which would have been written to the final string if
enough space had been available
This was found using CodeQL:
Potential fix for code scanning alerts (6,7,8):
Potentially overflowing call to snprintf

z_api_demo: Harden zwave_api_demo_callbacks.c by checking snprintf

---

applications/zpc/components/zwave_command_classes/src/zwave_command_class_meter_control.c
applications/zpc/components/zwave_command_classes/test/zwave_command_class_meter_control_test.c

Also fix related test, to always fail:
102 - zwave_command_class_meter_control_test (Failed)
For some reason I dont remember seeing it failed
despite the read should be invalid, this should be triggered by CI
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/issues/110#issuecomment-2916504388
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/pull/111#issuecomment-2916256186
Thanks-to: Laudin Molina Troconis <laudin.molinatroconis@silabs.com>
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/10

fix(cc): Fix meter_control_test check on frame without cmd

---

applications/zpc/components/zpc_utils/src/zpc_converters.c

Checking snprintf results, reminder :
If the output was truncated due to this limit, then the return
value is the number of characters (excluding the terminating
null byte) which would have been written to the final string if
enough space had been available
This was found using CodeQL:
Potential fix for code scanning alert no. 12:
Potentially overflowing call to snprintf

utils: Harden zpc_converters.c by checking snprintf

---

applications/zpc/applications/zwave_api_demo/src/zwave_api_demo_commands.c

Checking snprintf results, reminder :
If the output was truncated due to this limit, then the return
value is the number of characters (excluding the terminating
null byte) which would have been written to the final string if
enough space had been available
This was found using CodeQL:

z_api_demo: Harden zwave_api_demo_commands.c by checking snprintf

---

applications/zpc/components/zwave/zwave_controller/src/zwave_controller_utils.c

Checking snprintf results, reminder :
If the output was truncated due to this limit, then the return
value is the number of characters (excluding the terminating
null byte) which would have been written to the final string if
enough space had been available
This was found using CodeQL:
Potential fix for code scanning alert no. 13,14:
Potentially overflowing call to snprintf

controller: Harden zwave_controller_utils.c by checking snprintf

---

applications/zpc/components/zpc_stdin/src/zpc_stdin_command_handling.cpp
applications/zpc/components/zpc_stdin/test/zpc_stdin_test.c
applications/zpc/components/zwave/zwave_transports/s2/src/zwave_s2_network.c
applications/zpc/components/zwave/zwave_transports/s2/test/zwave_s2_network_test.c
applications/zpc/components/zwave_api/include/zwapi_protocol_controller.h
applications/zpc/components/zwave_api/src/zwapi_protocol_controller.c
applications/zpc/components/zwave_api/test/zwapi_protocol_controller_test.c

Specification change has been merged:
https://github.com/Z-Wave-Alliance/CSWG/blob/5f137ca1867a359a0523d63d9b2bd1bf2233f4d4/documents/zw-host-api-spec/source/zwave_api_commands/network_management/controller_nodes/get_node_nls_state_command.rst#L4

SWPROT-9430: Update Get Node NLS State SAPI command

---

applications/zpc/components/zwave_api/src/zwapi_connection.c
applications/zpc/components/zwave_api/test/CMakeLists.txt
applications/zpc/components/zwave_api/test/zwapi_connection_test.c

Change is obvious, it prevent an overflow,
note that functions did not test all inputs params specially when it is done in caller
(eg: in  zwave_api_send_data reject frames above limit).
Bug-SiliconLabs: UIC-3666
Bug-SLVDBBP: 3169925

fix(zwapi) Harden zwapi_connection_tx in zwapi_connection.c

---

applications/zpc/components/zwave_api/src/zwapi_init.c
applications/zpc/components/zwave_api/test/zwapi_init_test.c

This fix isolated to test the following test (with and without/revert) it.
The issue should be detected sooner (before calling zwapi_session_flush_queue)
2025-Jun-20 16:34:15.434395 <E> [zwapi_init] zwapi_refresh_capabilities: invalid supported_bitmask
By the way, It has been observed that using z-wave-stack-binaries length is clamped from 33 to 31 (this is unexpected, it could be caused by non aligned defs).
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/pull/125
Bug-SiliconLabs: UIC-3664
Relate-to: SLVDBBP-3162484
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/42

fix(zwapi): Prevent injection while refreshing caps

---

applications/zpc/components/zwave/zwave_transports/s2/libs/zw-libs2/protocol/S2.c

This is a simple change to check the static analysis.
SonarQube is reporting:
This "memset" is likely to be optimized away by the compiler; either remove it or replace it with "memset_s".
While memset_s is suggested it is not implemented widely (it is optional), at this stage i am following GNU standards until it stabilizes.
Relate-to: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1967.htm
Relate-to: https://en.cppreference.com/w/c/string/byte/memset
Relate-to: https://sourceware.org/glibc/manual/2.41/html_node/Erasing-Sensitive-Data.html
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/42

fix(s2): Harden S2_init_ctx using safe memset

---

applications/zpc/components/zwave_api/src/zwapi_init.c
applications/zpc/components/zwave_command_handler/src/zwave_command_handler.cpp

The previous change (85e13a715f586a3fac6280398d05690cb2a07e3e) introduced a MLK, and it passed reviews :)
Origin: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/pull/124
Bug-SiliconLabs: UIC-3668
Relate-to: SLVDBBP-3169975
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/42
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/pull/124

zapi: Harden more dispatch to prevent invalid data and fix MLK

---

applications/zpc/components/zwave/zwave_transports/s2/libs/zw-libs2/protocol/S2.c

The previously introduced patch break MacOS support, this transition code to C23 make it usable on both OS (Linux, MacOS).
Note that current version of gcc-12 in debian stable is not supporting this C23 function, so it fallback to the safer option for memset in this release.
Origin: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/pull/92
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/85
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/pull/137

fix(s2): Support C23 for secure memset (for MacOS clang-17)
